language: node_js
node_js:
- '7'
sudo: false
dist: trusty
branches:
  only:
  - master
  - develop
  - production
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
addons:
  chrome: stable
cache:
  yarn: true
before_install:
- pip install --user awscli
jobs:
  include:
  - stage: Test
    script: yarn test
  - stage: Build and deploy
    script: yarn build
deploy:
  provider: s3
  access_key_id: AKIAJX6HJMDFWU4CAC7A
  secret_access_key:
    secure: AQqX+stiGu0LAC8v5hLkjpSzB1KI8GDa3GDa34RQodkVcPePSEPK1dRBDdQwYxTW8tLpXuuJ6GIXgTudokDIO0yoOHAuAPOG22TrcjsxfPBS0MiDd2Kgt/323RgenPDbgPy1hGw8QXBeVcLNIlUKh+O1isAan51x7uDcYpbg1tE4syNnAnrjb4Gf4k6wvvxvcdnJZxvbhRZB72xBFYVqQiQJ64KAhf392+VPIY9+E/le4J5AxxF/fMPIjQymtazKwvCdhrRG+y694rLIGn2Yxhd8LaImC+IE3r7bbLklBnkD1rQ/zRAmWmMI/fbV9i+jkem5S0ZEZZJLzvoPD8xtjDEDhpNnmpr5PgSvpr40xh/rQouoeWHA/ky6sQO3cbpdwFiuzyi8gMyIz6swzJdiCEgI0BO3jX0F9lurTxruUErf7rEW3aL7V6kFiYeqGEIsji4bjaFDRHjw40pYWt+uoA5a6XnxvPGGMLZvHChYycE/mQ1qewwNVNKGy2NTIjQArYmnc1aPEkzz0HMt2t1L2xivYSuR51NHcHP5YOGuI1XfunheXr/LmLGLTSt/0Kj6Xb8NDIREggRJ9TnBMrVB82Q7fsHuc7uaXsgH3jZbv59pH6DOJXvt3bza4wdfJp55WFh1PuDEeyonTHjRy62Zm1A0883RutLngLk/uWP6aZI=
  bucket: successlink-media
  local-dir: dist/
  acl: public_read
  on:
    repo: CityOfBoston/successlink-frontend
